const currencyCode=[
  { id:0, code: "AED", name: "UAE Dirham", country: "United Arab Emirates" },
  { id:1, code: "AFN", name: "Afghan Afghani", country: "Afghanistan" },
  { id:2, code: "ALL", name: "Albanian Lek", country: "Albania" },
  { id:3, code: "AMD", name: "Armenian Dram", country: "Armenia" },
  { id:4, code: "AOA", name: "Angolan Kwanza", country: "Angola" },
  { id:5, code: "ARS", name: "Argentine Peso", country: "Argentina" },
  { id:6, code: "AUD", name: "Australian Dollar", country: "Australia" },
  { id:7, code: "AWG", name: "Aruban Florin", country: "Aruba" },
  { id:8, code: "AZN", name: "Azerbaijani Manat", country: "Azerbaijan" },
  { id:9, code: "BAM", name: "Bosnia Herzegovina Convertible Mark", country: "Bosnia and Herzegovina" },
  { id:10, code: "BBD", name: "Barbadian Dollar", country: "Barbados" },
  { id:11, code: "BDT", name: "Bangladeshi Taka", country: "Bangladesh" },
  { id:12, code: "BGN", name: "Bulgarian Lev", country: "Bulgaria" },
  { id:13, code: "BHD", name: "Bahraini Dinar", country: "Bahrain" },
  { id:14, code: "BIF", name: "Burundian Franc", country: "Burundi" },
  { id:15, code: "BMD", name: "Bermudian Dollar", country: "Bermuda" },
  { id:16, code: "BND", name: "Brunei Dollar", country: "Brunei" },
  { id:17, code: "BOB", name: "Bolivian Boliviano", country: "Bolivia" },
  { id:18, code: "BRL", name: "Brazilian Real", country: "Brazil" },
  { id:19, code: "BSD", name: "Bahamian Dollar", country: "Bahamas" },
  { id:20, code: "BTN", name: "Bhutanese Ngultrum", country: "Bhutan" },
  { id:21, code: "BWP", name: "Botswana Pula", country: "Botswana" },
  { id:22, code: "BYN", name: "Belarusian Ruble", country: "Belarus" },
  { id:23, code: "BZD", name: "Belize Dollar", country: "Belize" },
  { id:24, code: "CAD", name: "Canadian Dollar", country: "Canada" },
  { id:25, code: "CDF", name: "Congolese Franc", country: "Democratic Republic of the Congo" },
  { id:26, code: "CHF", name: "Swiss Franc", country: "Switzerland" },
  { id:27, code: "CLP", name: "Chilean Peso", country: "Chile" },
  { id:28, code: "CNY", name: "Chinese Yuan", country: "China" },
  { id:29, code: "COP", name: "Colombian Peso", country: "Colombia" },
  { id:30, code: "CRC", name: "Costa Rican Colón", country: "Costa Rica" },
  { id:31, code: "CUP", name: "Cuban Peso", country: "Cuba" },
  { id:32, code: "CVE", name: "Cape Verdean Escudo", country: "Cape Verde" },
  { id:33, code: "CZK", name: "Czech Koruna", country: "Czech Republic" },
  { id:34, code: "DJF", name: "Djiboutian Franc", country: "Djibouti" },
  { id:35, code: "DKK", name: "Danish Krone", country: "Denmark" },
  { id:36, code: "DOP", name: "Dominican Peso", country: "Dominican Republic" },
  { id:37, code: "DZD", name: "Algerian Dinar", country: "Algeria" },
  { id:38, code: "EGP", name: "Egyptian Pound", country: "Egypt" },
  { id:39, code: "ERN", name: "Eritrean Nakfa", country: "Eritrea" },
  { id:40, code: "ETB", name: "Ethiopian Birr", country: "Ethiopia" },
  { id:41, code: "EUR", name: "Euro", country: "European Union" },
  { id:42, code: "FJD", name: "Fijian Dollar", country: "Fiji" },
  { id:43, code: "FKP", name: "Falkland Islands Pound", country: "Falkland Islands" },
  { id:44, code: "FOK", name: "Faroese Króna", country: "Faroe Islands" },
  { id:45, code: "GBP", name: "British Pound", country: "United Kingdom" },
  { id:46, code: "GEL", name: "Georgian Lari", country: "Georgia" },
  { id:47, code: "GGP", name: "Guernsey Pound", country: "Guernsey" },
  { id:48, code: "GHS", name: "Ghanaian Cedi", country: "Ghana" },
  { id:49, code: "GIP", name: "Gibraltar Pound", country: "Gibraltar" },
  { id:50, code: "GMD", name: "Gambian Dalasi", country: "Gambia" },
  { id:51, code: "GNF", name: "Guinean Franc", country: "Guinea" },
  { id:52, code: "GTQ", name: "Guatemalan Quetzal", country: "Guatemala" },
  { id:53, code: "GYD", name: "Guyanese Dollar", country: "Guyana" },
  { id:54, code: "HKD", name: "Hong Kong Dollar", country: "Hong Kong" },
  { id:55, code: "HNL", name: "Honduran Lempira", country: "Honduras" },
  { id:56, code: "HRK", name: "Croatian Kuna", country: "Croatia" },
  { id:57, code: "HTG", name: "Haitian Gourde", country: "Haiti" },
  { id:58, code: "HUF", name: "Hungarian Forint", country: "Hungary" },
  { id:59, code: "IDR", name: "Indonesian Rupiah", country: "Indonesia" },
  { id:60, code: "ILS", name: "Israeli New Shekel", country: "Israel" },
  { id:61, code: "IMP", name: "Isle of Man Pound", country: "Isle of Man" },
  { id:62, code: "INR", name: "Indian Rupee", country: "India" },
  { id:63, code: "IQD", name: "Iraqi Dinar", country: "Iraq" },
  { id:64, code: "IRR", name: "Iranian Rial", country: "Iran" },
  { id:65, code: "ISK", name: "Icelandic Króna", country: "Iceland" },
  { id:66, code: "JMD", name: "Jamaican Dollar", country: "Jamaica" },
  { id:67, code: "JOD", name: "Jordanian Dinar", country: "Jordan" },
  { id:68, code: "JPY", name: "Japanese Yen", country: "Japan" },
  { id:69, code: "KES", name: "Kenyan Shilling", country: "Kenya" },
  { id:70, code: "KGS", name: "Kyrgystani Som", country: "Kyrgyzstan" },
  { id:71, code: "KHR", name: "Cambodian Riel", country: "Cambodia" },
  { id:72, code: "KMF", name: "Comorian Franc", country: "Comoros" },
  { id:73, code: "KRW", name: "South Korean Won", country: "South Korea" },
  { id:74, code: "KWD", name: "Kuwaiti Dinar", country: "Kuwait" },
  { id:75, code: "KYD", name: "Cayman Islands Dollar", country: "Cayman Islands" },
  { id:76, code: "KZT", name: "Kazakhstani Tenge", country: "Kazakhstan" },
  { id:77, code: "LAK", name: "Laotian Kip", country: "Laos" },
  { id:78, code: "LBP", name: "Lebanese Pound", country: "Lebanon" },
  { id:79, code: "LKR", name: "Sri Lankan Rupee", country: "Sri Lanka" },
  { id:80, code: "LRD", name: "Liberian Dollar", country: "Liberia" },
  { id:81, code: "LSL", name: "Lesotho Loti", country: "Lesotho" },
  { id:82, code: "LYD", name: "Libyan Dinar", country: "Libya" },
  { id:83, code: "MAD", name: "Moroccan Dirham", country: "Morocco" },
  { id:84, code: "MDL", name: "Moldovan Leu", country: "Moldova" },
  { id:85, code: "MGA", name: "Malagasy Ariary", country: "Madagascar" },
  { id:86, code: "MKD", name: "Macedonian Denar", country: "North Macedonia" },
  { id:87, code: "MMK", name: "Myanmar Kyat", country: "Myanmar" },
  { id:88, code: "MNT", name: "Mongolian Tugrik", country: "Mongolia" },
  { id:89, code: "MOP", name: "Macanese Pataca", country: "Macau" },
  { id:90, code: "MRU", name: "Mauritanian Ouguiya", country: "Mauritania" },
  { id:91, code: "MUR", name: "Mauritian Rupee", country: "Mauritius" },
  { id:92, code: "MVR", name: "Maldivian Rufiyaa", country: "Maldives" },
  { id:93, code: "MWK", name: "Malawian Kwacha", country: "Malawi" },
  { id:94, code: "MXN", name: "Mexican Peso", country: "Mexico" },
  { id:95, code: "MYR", name: "Malaysian Ringgit", country: "Malaysia" },
  { id:96, code: "MZN", name: "Mozambican Metical", country: "Mozambique" },
  { id:97, code: "NAD", name: "Namibian Dollar", country: "Namibia" },
  { id:98, code: "NGN", name: "Nigerian Naira", country: "Nigeria" },
  { id:99, code: "NIO", name: "Nicaraguan Córdoba", country: "Nicaragua" },
  { id: 100, code: "NOK", name: "Norwegian Krone", country: "Norway" },
  { id: 101, code: "NPR", name: "Nepalese Rupee", country: "Nepal" },
  { id: 102, code: "NZD", name: "New Zealand Dollar", country: "New Zealand" },
  { id: 103, code: "OMR", name: "Omani Rial", country: "Oman" },
  { id: 104, code: "PAB", name: "Panamanian Balboa", country: "Panama" },
  { id: 105, code: "PEN", name: "Peruvian Sol", country: "Peru" },
  { id: 106, code: "PGK", name: "Papua New Guinean Kina", country: "Papua New Guinea" },
  { id: 107, code: "PHP", name: "Philippine Peso", country: "Philippines" },
  { id: 108, code: "PKR", name: "Pakistani Rupee", country: "Pakistan" },
  { id: 109, code: "PLN", name: "Polish Złoty", country: "Poland" },
  { id: 110, code: "PYG", name: "Paraguayan Guarani", country: "Paraguay" },
  { id: 111, code: "QAR", name: "Qatari Rial", country: "Qatar" },
  { id: 112, code: "RON", name: "Romanian Leu", country: "Romania" },
  { id: 113, code: "RSD", name: "Serbian Dinar", country: "Serbia" },
  { id: 114, code: "RUB", name: "Russian Ruble", country: "Russia" },
  { id: 115, code: "RWF", name: "Rwandan Franc", country: "Rwanda" },
  { id: 116, code: "SAR", name: "Saudi Riyal", country: "Saudi Arabia" },
  { id: 117, code: "SBD", name: "Solomon Islands Dollar", country: "Solomon Islands" },
  { id: 118, code: "SCR", name: "Seychellois Rupee", country: "Seychelles" },
  { id: 119, code: "SDG", name: "Sudanese Pound", country: "Sudan" },
  { id: 120, code: "SEK", name: "Swedish Krona", country: "Sweden" },
  { id: 121, code: "SGD", name: "Singapore Dollar", country: "Singapore" },
  { id: 122, code: "SHP", name: "Saint Helena Pound", country: "Saint Helena" },
  { id: 123, code: "SLE", name: "Sierra Leonean Leone", country: "Sierra Leone" },
  { id: 124, code: "SOS", name: "Somali Shilling", country: "Somalia" },
  { id: 125, code: "SRD", name: "Surinamese Dollar", country: "Suriname" },
  { id: 126, code: "SSP", name: "South Sudanese Pound", country: "South Sudan" },
  { id: 127, code: "STN", name: "São Tomé and Príncipe Dobra", country: "São Tomé and Príncipe" },
  { id: 128, code: "SYP", name: "Syrian Pound", country: "Syria" },
  { id: 129, code: "SZL", name: "Eswatini Lilangeni", country: "Eswatini" },
  { id: 130, code: "THB", name: "Thai Baht", country: "Thailand" },
  { id: 131, code: "TJS", name: "Tajikistani Somoni", country: "Tajikistan" },
  { id: 132, code: "TMT", name: "Turkmenistani Manat", country: "Turkmenistan" },
  { id: 133, code: "TND", name: "Tunisian Dinar", country: "Tunisia" },
  { id: 134, code: "TOP", name: "Tongan Paʻanga", country: "Tonga" },
  { id: 135, code: "TRY", name: "Turkish Lira", country: "Turkey" },
  { id: 136, code: "TTD", name: "Trinidad and Tobago Dollar", country: "Trinidad and Tobago" },
  { id: 137, code: "TWD", name: "New Taiwan Dollar", country: "Taiwan" },
  { id: 138, code: "TZS", name: "Tanzanian Shilling", country: "Tanzania" },
  { id: 139, code: "UAH", name: "Ukrainian Hryvnia", country: "Ukraine" },
  { id: 140, code: "UGX", name: "Ugandan Shilling", country: "Uganda" },
  { id: 141, code: "USD", name: "United States Dollar", country: "United States" },
  { id: 142, code: "UYU", name: "Uruguayan Peso", country: "Uruguay" },
  { id: 143, code: "UZS", name: "Uzbekistani Soʻm", country: "Uzbekistan" },
  { id: 144, code: "VES", name: "Venezuelan Bolívar Soberano", country: "Venezuela" },
  { id: 145, code: "VND", name: "Vietnamese Đồng", country: "Vietnam" },
  { id: 146, code: "VUV", name: "Vanuatu Vatu", country: "Vanuatu" },
  { id: 147, code: "WST", name: "Samoan Tālā", country: "Samoa" },
  { id: 148, code: "XAF", name: "Central African CFA Franc", country: "Central African Republic" },
  { id: 149, code: "XCD", name: "East Caribbean Dollar", country: "East Caribbean Countries" },
  { id: 150, code: "XDR", name: "IMF Special Drawing Rights", country: "International Monetary Fund" },
  { id: 151, code: "XOF", name: "West African CFA Franc", country: "West African Countries" },
  { id: 152, code: "XPF", name: "CFP Franc", country: "Pacific Territories" },
  { id: 153, code: "YER", name: "Yemeni Rial", country: "Yemen" },
  { id: 154, code: "ZAR", name: "South African Rand", country: "South Africa" },
  { id: 155, code: "ZMW", name: "Zambian Kwacha", country: "Zambia" },
  { id: 156, code: "ZWL", name: "Zimbabwean Dollar", country: "Zimbabwe" }

]


export default currencyCode;